language: python
python:
  - "2.7"

git:
  depth: 3

before_install:
  - sudo -H apt-get update -qq

install:
  - sudo -H pip install http://releases.ansible.com/ansible/ansible-2.2.1.0.tar.gz
  - echo -e 'localhost  ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg

script:
  - ansible-playbook --syntax-check tests/role.yml
  - ansible-playbook -v --diff tests/role.yml
  - >
    ansible-playbook tests/role.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
