---
- name: "autoremove"
  become: true
  command: "apt-get -y autoremove"

- name: "autoclean"
  become: true
  command: "apt-get -y autoclean"

- name: "clean packages"
  become: true
  command: "apt-get -y clean"

# From http://askubuntu.com/a/3169
#
# clean: clean clears out the local repository of retrieved package files.
#   It removes everything but the lock file from /var/cache/apt/archives/ and /var/cache/apt/archives/partial/.
#   When APT is used as a dselect(1) method, clean is run automatically.
#   Those who do not use dselect will likely want to run apt-get clean from time to time to free up disk space.
#
# autoclean: Like clean, autoclean clears out the local repository of retrieved package files.
#   The difference is that it only removes package files that can no longer be downloaded, and are largely useless.
#   This allows a cache to be maintained over a long period without it growing out of control.
#   The configuration option APT::Clean-Installed will prevent installed packages from being erased if it is set to off.
#
# autoremove: is used to remove packages that were automatically installed to satisfy
#   dependencies for some package and that are no more needed.